apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 3
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "caioq/sample-go-kubernetes:v5.1"
          envFrom:
            - configMapRef:
                name: goserver-env
          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef: 
          #         name: goserver-env
          #         key: NAME

          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config


      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"