apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 3
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "caioq/sample-go-kubernetes:v3"
          envFrom:
            - configMapRef:
                name: goserver-env
          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef: 
          #         name: goserver-env
          #         key: NAME