apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  # type: ClusterIP
  type: LoadBalancer
  ports:
  - name: goserver-service
    port: 8001
    protocol: TCP

